### ISSUE TITLE
Document and/or move IndefiniteSubject

### ISSUE THREAD

**Issue by appsforartists** [material-motion/indefinite-observable-js#14]
`IndefiniteSubject` isn't documented in the README and hasn't been implemented in Swift/Java.  `IndefiniteObservable` has.  Therefore, v1.0.0 is blocked by documentation here and implementation across the platforms.

Potential solutions:

- Fork the present repo into `indefinite-subject`, delete the `indefinite-observable` code, and depend on `indefinite-observable` for types and `wrapWithObserver`.
- Move `indefinite-subject` into `materal-motion-js/packages`.
- Move `IndefiniteSubject.ts` (and the associated tests) into `material-motion-js/packages/streams`

**Comment by jverkoey** [comment]
"Move IndefiniteSubject.ts (and the associated tests) into material-motion-js/packages/streams" is my preferred solution here because it creates the minimal amount of immediate overhead.

**Comment by appsforartists** [comment]
🎊 My diff is ready for review at http://codereview.cc/D2496
