### ISSUE TITLE
Write unit tests

### ISSUE THREAD

**Issue by jverkoey** [material-motion/indefinite-observable-js#3]

**Comment by appsforartists** [comment]
# Test ideas:

1. Can unsubscribe be called only once per subscription?
1. What happens if you have a chain of streams and call unsubscribe/subscribe/unsubscribe/subscribe?
    - Does this match the behavior of xstream and rx?
1. Does the creator have to return an unsubscribe?
1. Do two observers to a synchronous creator each receive the value?

**Comment by appsforartists** [comment]
🎊 My diff is ready for review at http://codereview.cc/D2214
