### ISSUE TITLE
Return subscription from creator

### ISSUE THREAD

**Issue by appsforartists** [material-motion/indefinite-observable-js#4]
From @jverkoey's over-the-shoulder code review.

https://github.com/tc39/proposal-observable

**Comment by appsforartists** [comment]
@jverkoey, according to spec, creators don't return subscriptions:

"The subscriber function is called with a wrapped observer object and may optionally return a function which will cancel the subscription."

**Comment by jverkoey** [comment]
Hm. I suppose the Subscription gets created by the Observable then?

**Comment by appsforartists** [comment]
Seems that way:

https://github.com/ReactiveX/rxjs/blob/master/src/Subscriber.ts#L126
https://github.com/zenparsing/zen-observable/blob/master/src/Observable.js#L254

**Comment by appsforartists** [comment]
<aside>
  Every time I try to read the source of one of these libraries, I'm thankful for `IndefiniteObservable`
</aside>

**Comment by jverkoey** [comment]
Lol

**Comment by jverkoey** [comment]
Just updated the .swift impl to match the spec.

**Comment by jverkoey** [comment]
http://codereview.cc/D2096
